--SELECT * FROM EMPLOYEES;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID=101;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID<110;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID>200;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID>=200;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID<=150;
--SELECT * FROM EMPLOYEES WHERE MANAGER_ID<>114;
--
--SELECT FIRST_NAME, SALARY, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID = 'AD_VP' AND DEPARTMENT_ID = 90;
--SELECT FIRST_NAME, SALARY, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID = 'AD VP' OR DEPARTMENT_ID = 90;
--SELECT FIRST_NAME, SALARY, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE Not JOB_ID = 'AD VP';
--
--SELECT SALARY,COMMISSION_PCT, ((SALARY+COMMISSION_PCT)*SALARY) FROM EMPLOYEES where Commission_pct IS NOT NULL ORDER BY ((SALARY+COMMISSION_PCT)*SALARY);

select * from EMPLOYEES;

select max(SALARY) FROM EMPLOYEES WHERE JOB_ID='SA_MAN';
select MIN(SALARY) FROM EMPLOYEES WHERE JOB_ID='SA_MAN';

SELECT *FROM EMPLOYEES WHERE HIRE_DATE>'15-NOV-06';

SELECT *FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 6000;

SELECT JOB_ID FROM EMPLOYEES WHERE SALARY <= 3200;

SELECT employee_id,first_name,last_name,department_id from EMPLOYEES where first_name='Pat';

SELECT employee_id,first_name,last_name,department_id from EMPLOYEES where department_id=100 ;

select phone_number from EMPLOYEES where DEPARTMENT_ID=30 and MANAGER_ID<>114;

select LAST_NAME,salary from EMPLOYEES where LAST_NAME in ('Chen','Baida','Himuro')



hey this is my first time on github
trying to understand it which tbh is kinda difficult
well really difficult frrrrrrr




